# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_tidySEabstraction_wrappers", use_symbols = TRUE, package_name = "tidySEabstraction")

#' @docType package
#' @usage NULL
#' @useDynLib tidySEabstraction, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' @param x an integer array
#' @param y an integer array
#' @export
add2_slice <- function(x, y) .Call(wrap__add2_slice, x, y)

#' example of how to modifiy R objects
#' inplace
#' @param x an integer R object
#' @export
mutate_first <- function(x) invisible(.Call(wrap__mutate_first, x))


# nolint end
